/* eslint-disable prettier/prettier */

'use client';

import Link from 'next/link';
import { CtaSection } from './CtaSection';
import { SiteHeader } from './SiteHeader';
import { SiteFooter } from './SiteFooter';
import { useMarketingLocale } from './MarketingLocaleProvider';
import { VERTICALS_DATA } from '@/app/verticali/[slug]/verticals-data';

const trCopy: Record<string, { title: string; eyebrow: string; h1: string; body: string; metric: string; pains: [string,string][]; scenarios: [string,string][] }> = {
 salon: { title:'Kuaför ve Berber', eyebrow:'Kuaför ve Berber', h1:'Randevu taleplerini kesinleşmiş randevulara dönüştürün.', body:'Hizmet sorularını yanıtlayın, randevu için gereken bilgileri alın, gerçek uygunluğu kontrol edin ve gerektiğinde personelinize aktarın.', metric:'Müşteri mesajlarını 7/24 karşılama', pains:[['Yoğun resepsiyon','Tekrarlanan randevu sorularını personelin her mesaja yanıt vermesini gerektirmeden yönetin.'],['Çakışan randevular','Saat önermeden önce hizmet süresini, çalışma saatlerini ve takvim uygunluğunu kontrol edin.'],['Mesai dışı talepler','Mesai dışında gelen talepleri takip için kaydedin.']], scenarios:[['Yeni randevu','Asistan uygunluğu kontrol eder ve geçerli saat seçeneklerini sunar.'],['Randevu değiştirme','Mevcut randevuyu bulur, alternatifleri kontrol eder ve günceller.'],['İnsanla görüşme','Otomasyon durur ve görüşme bağlamıyla personele aktarılır.']] },
 beauty: { title:'Güzellik ve Bakım', eyebrow:'Güzellik ve Bakım', h1:'Bakım taleplerini randevuya dönüştürmeyi kolaylaştırın.', body:'Hizmete özel bilgileri, süreleri ve işletme kurallarını kullanarak müşterileri geçerli randevu seçeneklerine yönlendirin.', metric:'Gerçek uygunluğa dayalı randevu akışı', pains:[['Çok sayıda hizmet','İşletmenin bilgi tabanından tutarlı yanıtlar verin.'],['Farklı hizmet süreleri','Randevu uygunluğunu her hizmet için tanımlanan süreyle uyumlu tutun.'],['Politika soruları','İptal ve hazırlık sorularını onaylı bilgilerle yanıtlayın.']], scenarios:[['Bakım hakkında soru','Onaylı hizmet açıklamasını aktarın ve gerekli bilgileri sorun.'],['Tercih edilen saat','Saat önermeden önce gerçek takvimi kontrol edin.'],['Belirsiz talep','Açıklama isteyin veya talebi yetkili kişiye aktarın.']] },
 dental: { title:'Diş ve Klinik', eyebrow:'Diş ve Klinik', h1:'Klinik uzmanı gibi davranmadan randevuları düzenleyin.', body:'İdari soruları ve randevu taleplerini yönetin; tanı koymayın veya tedavi tavsiyesi vermeyin.', metric:'Güvenli idari randevu sınırları', pains:[['Randevu yoğunluğu','Personelin müdahalesinden önce randevu ayrıntılarını toplayın.'],['Hassas sorular','İdari desteğin dışındaki talepleri insan desteğine aktarın.'],['Eksik bilgiler','Tahmin etmek yerine gerekli randevu bilgilerini sorun.']], scenarios:[['Rutin randevu','Hizmet talebini toplayın ve uygunluğu kontrol edin.'],['Klinik soru','Yanıt uydurmak yerine insan desteğine aktarın.'],['Randevu değiştirme','Randevuyu yalnızca geçerli alternatif bulunduğunda değiştirin.']] },
 veterinary: { title:'Veteriner', eyebrow:'Veteriner', h1:'Evcil hayvan randevularını gerçek takvime göre düzenleyin.', body:'Hayvan ve sahibiyle ilgili randevu bilgilerini toplayın, onaylı işletme sorularını yanıtlayın ve veteriner personeli gerektiren durumları aktarın.', metric:'İdari talepleri 7/24 karşılama', pains:[['Eksik bilgiler','Talebi personele aktarmadan önce gerekli bilgileri toplayın.'],['Acil talepler','Tanı veya tedavi tavsiyesi vermek yerine aktarım kurallarını uygulayın.'],['Takvim çakışmaları','Saat önermeden önce uygunluğu kontrol edin.']], scenarios:[['Rutin ziyaret','Randevu nedenini ve saati alın, uygun seçenekleri sunun.'],['Acil endişe','Tıbbi tavsiye vermeden talebi personele aktarın.'],['Kontrol randevusu','Tanımlanan hizmet ve takvim üzerinden takip randevusu oluşturun.']] },
 fitness: { title:'Spor Salonu ve Fitness', eyebrow:'Spor Salonu ve Fitness', h1:'Personeli mesaj trafiğine boğmadan randevuları planlayın.', body:'Danışmanlık, kişisel antrenman ve diğer hizmetleri gerçek uygunluğa göre koordine edin.', metric:'Uygunluğa dayalı planlama', pains:[['Birden çok hizmet','Hizmet sürelerini ve randevu kurallarını tutarlı tutun.'],['Antrenör takvimleri','Personelin tanımlı uygunluğuna uyun.'],['Geç gelen talepler','Mesai dışındaki talepleri doğru iş akışına yönlendirin.']], scenarios:[['Antrenman talebi','İstenen hizmeti uygun saatle eşleştirin.'],['Program değişikliği','Randevuyu değiştirmeden önce alternatifleri kontrol edin.'],['Personele aktarma','Antrenör gerektiren soruları personele aktarın.']] },
 'auto-service': { title:'Oto Servis', eyebrow:'Oto Servis', h1:'Servis taleplerini yapılandırılmış randevulara dönüştürün.', body:'Servis planlaması için gereken bilgileri toplayın, süre ve kaynakları kontrol edin, teknik soruları personele aktarın.', metric:'Talepten randevuya iş akışı', pains:[['Düzensiz talepler','Müşteri mesajlarını planlama ayrıntılarına dönüştürün.'],['Kaynak çakışmaları','Randevuları uygun servis alanı ve personelle eşleştirin.'],['Teknik sorular','Belirsiz teknik soruları tahmin etmek yerine personele aktarın.']], scenarios:[['Servis randevusu','Talep ve araç bilgilerini alın, uygunluğu kontrol edin.'],['Onarım sorusu','Doğrulanmamış teşhis sunmak yerine teknik soruları aktarın.'],['Randevu değiştirme','Yeni saatin uygunluğunu kontrol ettikten sonra değişiklik yapın.']] },
 consulting: { title:'Danışmanlık ve Profesyonel Hizmetler', eyebrow:'Danışmanlık', h1:'Görüşme taleplerini takvime ulaşmadan önce nitelendirin.', body:'İşletmenin onayladığı bilgileri toplayın, bilinen soruları yanıtlayın, görüşmeleri planlayın ve karmaşık talepleri bir kişiye aktarın.', metric:'Müşteri adayından görüşmeye iş akışı', pains:[['Bağlamı eksik görüşmeler','Randevudan önce gerekli temel bilgileri toplayın.'],['Takvim için yazışmalar','Yalnızca takvimdeki geçerli saatleri sunun.'],['Hassas talepler','Otomatik yönetilmemesi gereken konuları bir kişiye aktarın.']], scenarios:[['Tanışma görüşmesi','Gerekli bilgileri alın ve uygun bir görüşme planlayın.'],['Mevcut müşteri','Talepleri işletme kurallarına göre yönlendirin.'],['Özel talep','Bilgi tabanı yetersizse talebi bir kişiye aktarın.']] }
};

export function VerticalDetailClient({ slug }: { slug: string }) {
 const { language, t } = useMarketingLocale();
 const data = VERTICALS_DATA[slug];
 if (data === undefined) return null;
 const translated = language === 'tr' ? trCopy[slug] : undefined;
 const pains = translated ? translated.pains : data.pains.map((x) => [x.title, x.body] as [string,string]);
 const scenarios = translated ? translated.scenarios : data.scenarios.map((x) => [x.title, x.body] as [string,string]);
 const others = Object.values(VERTICALS_DATA).filter((v) => v.slug !== slug);
 return <><SiteHeader /><main id="main"><section className="hero"><div className="container hero-grid"><div className="stack stack-6"><span className="hero-eyebrow">{data.icon} {translated?.eyebrow ?? data.hero.eyebrow}</span><h1 className="display text-balance">{translated?.h1 ?? data.hero.h1}</h1><p className="lead">{translated?.body ?? data.hero.body}</p><div className="row"><Link href={'/register?vertical=' + slug} className="btn btn-primary btn-lg">{language === 'tr' ? 'Kuruluma başlayın' : 'Start setup'}</Link><Link href={'/pricing?ref=vertical-' + slug} className="btn btn-secondary btn-lg">{t.viewPlans}</Link></div><div className="card stack stack-2"><span className="eyebrow">{language === 'tr' ? 'İş akışının odağı' : 'Workflow focus'}</span><p>{data.metric.value}</p><p className="muted">{translated?.metric ?? data.metric.label}</p></div></div><div className="card card-padded stack stack-4"><span className="eyebrow">{language === 'tr' ? 'Örnek iş akışı' : 'Example workflow'}</span>{scenarios.map(([title,body],i)=><div key={title} className="stack stack-2"><strong>{String(i+1).padStart(2,'0')} · {title}</strong><p className="muted">{body}</p></div>)}</div></div></section><section className="section section-divider"><div className="container stack stack-6"><h2>{language === 'tr' ? 'Çözdüğü sorunlar' : 'Problems it addresses'}</h2><div className="feature-grid">{pains.map(([title,body])=><article key={title} className="card stack stack-3"><h3>{title}</h3><p>{body}</p></article>)}</div></div></section><section className="section section-divider"><div className="container stack stack-6"><h2>{language === 'tr' ? 'Diğer sektör şablonları' : 'Other sector presets'}</h2><div className="row">{others.map((v)=><Link key={v.slug} href={'/verticali/' + v.slug} className="btn btn-secondary">{language === 'tr' ? (trCopy[v.slug]?.title ?? v.title) : v.title}</Link>)}</div></div></section><CtaSection /></main><SiteFooter /></>;
}
